# Generated by Django 4.2 on 2025-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('instagram_username', models.CharField(max_length=100, verbose_name='Instagram Username')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
    ]
