# Generated by Django 4.2 on 2025-07-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_birthdayclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер WhatsApp'),
        ),
    ]
