# Generated by Django 4.2 on 2025-10-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_birthdayclient_phone_number'),
    ]

    operations = [
    ]
